__name__ = 'pdf12step'
__title__ = '12 Step Meeting PDF Generator'
__version__ = '1.2.0'
__author__ = 'Justin Quick'
__author_email__ = 'justquick@gmail.com'
__url__ = 'https://github.com/justquick/pdf12step'
__license__ = 'BSD'
__description__ = 'Generates PDFs meeting guides from sites using the 12 Step Meeting List WordPress plugin'
