# Example config for half sized print version for phamplets
size:  5.5in 8.5in

# Black and white
color: white
header_color: "black"
page_number_color: white

# Font size and other fixes for smaller size
stylesheets:
    - assets/css/style.css
    - assets/css/print.css

# Disable links for printed edition
show_links: false

notes_pages: 2
